name: UTR_generation
channels: 
  - bioconda
  - plotly
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - bioconda::gffutils==0.10.*
  - seaborn
  - matplotlib
  - jupyter
  - conda-forge::biopython
  - plotly::plotly=4.5.*
  - pybedtools
  - bedtools
  - htslib
